@startuml

title __CONSTANTS's Class Diagram__\n

  package game {
    package game.constants {
      class ApplicationConstants {
          {static} + APP_FOLDER_DATA_PATH : String
          {static} + PATH_SEPARATOR : String
          {static} + DATABASE_NAME : String
          {static} + DATABASE_FOLDER : String
          {static} + SQLITE_JDBC : String
          {static} + DB_CONNECTION_URL : String
          {static} + TABLE_GAME_ARTIFACTS : String
          {static} + TABLE_GAME_ARTIFACTS_ID_COLUMN : String
          {static} + TABLE_GAME_ARTIFACTS_NAME_COLUMN : String
          {static} + TABLE_GAME_ARTIFACTS_COLLECTIBLE_COLUMN : String
          {static} + TABLE_ARTIFACTS_POSITION : String
          {static} + TABLE_ARTIFACTS_HORIZONTAL_POSITION : String
          {static} + TABLE_ARTIFACTS_VERTICAL_POSITION : String
          {static} + TABLE_ARTIFACTS_ID : String
          {static} + TABLE_ARTIFACTS_GAMEBOARD_ID : String
          {static} + TABLE_GAME_BOARDS : String
          {static} + TABLE_GAME_BOARDS_ID_COLUMN : String
          {static} + TABLE_GAME_BOARDS_NAME_COLUMN : String
          {static} + TABLE_GAME_BOARDS_SIZE_COLUMN : String
          {static} + TABLE_PLAYER_ID_COLUMN : String
          {static} + TABLE_PLAYER_NAME_COLUMN : String
          {static} + TABLE_PLAYERS : String
          {static} + TABLE_PLAYER_GAMEBOARD_ID : String
          {static} + TABLE_PLAYER_HORIZONTAL : String
          {static} + TABLE_PLAYER_VERTICAL : String
          {static} + TABLE_RELATED_BOARDS : String
          {static} + TABLE_RELATED_BOARDS_ID : String
          {static} + TABLE_RELATED_BOARDS_MAP : String
          {static} + TABLE_RELATED_HORIZONTAL_CONNECTION : String
          {static} + TABLE_RELATED_VERTICAL_CONNECTION : String
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
